In [ ]:
# Program to calculate Mean, Median, Mode, Variance, and Standard Deviation

import statistics

# Taking input from user
numbers = list(map(float, input("Enter numbers separated by space: ").split()))

# Mean
mean_value = statistics.mean(numbers)

# Median
median_value = statistics.median(numbers)

# Mode
try:
    mode_value = statistics.mode(numbers)
except statistics.StatisticsError:
    mode_value = "No unique mode"

# Variance
variance_value = statistics.variance(numbers)

# Standard Deviation
std_deviation = statistics.stdev(numbers)

# Display results
print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)


Enter numbers separated by space: 56 78 90 54 67 
Mean: 69.0
Median: 67.0
Mode: 56.0
Variance: 230.0
Standard Deviation: 15.165750888103101


In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:")
print(arr)

# 1. Find sum and mean
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))

# 2. Find maximum and minimum
print("\nMaximum:", np.max(arr))
print("Minimum:", np.min(arr))

# 3. Reshape the array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped Array (2x3):")
print(reshaped_arr)

# 4. Element-wise multiplication
# Multiply array with another array of same size
arr2 = np.array([1, 2, 3, 4, 5, 6])
multiplication = arr * arr2

print("\nSecond Array:")
print(arr2)

print("\nElement-wise Multiplication:")
print(multiplication)


Original Array:
[10 20 30 40 50 60]

Sum: 210
Mean: 35.0

Maximum: 60
Minimum: 10

Reshaped Array (2x3):
[[10 20 30]
 [40 50 60]]

Second Array:
[1 2 3 4 5 6]

Element-wise Multiplication:
[ 10  40  90 160 250 360]


In [ ]:
import numpy as np

# 1. Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[6, 5, 4],
                    [3, 2, 1]])

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# 2. Addition
addition = matrix1 + matrix2
print("\nAddition of Matrices:")
print(addition)

# 3. Subtraction
subtraction = matrix1 - matrix2
print("\nSubtraction of Matrices:")
print(subtraction)

# 4. Matrix Multiplication
matrix2_T = matrix2.T
multiplication = np.dot(matrix1, matrix2_T)
print("\nMatrix Multiplication (matrix1 * matrix2.T):")
print(multiplication)

# 5. Transpose of a matrix
transpose1 = matrix1.T
print("\nTranspose of Matrix 1:")
print(transpose1)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[6 5 4]
 [3 2 1]]

Addition of Matrices:
[[7 7 7]
 [7 7 7]]

Subtraction of Matrices:
[[-5 -3 -1]
 [ 1  3  5]]

Matrix Multiplication (matrix1 * matrix2.T):
[[28 10]
 [73 28]]

Transpose of Matrix 1:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

# Generate a random array of 10 numbers (0 to 100)
random_array = np.random.randint(0, 101, 10)
print("Random Array:")
print(random_array)

# Calculate Mean
mean_value = np.mean(random_array)
print("\nMean:", mean_value)

# Calculate Standard Deviation
std_dev = np.std(random_array)
print("Standard Deviation:", std_dev)

# Find Minimum and Maximum
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[48 93 66 36 85 78 20 59 58  2]

Mean: 54.5
Standard Deviation: 27.313915867191213
Minimum Value: 2
Maximum Value: 93


In [ ]:
from scipy import stats
import numpy as np

# Sample dataset
data = np.array([12, 15, 14, 10, 13, 15, 16])

# Calculate Mean using scipy.stats
mean_value = stats.tmean(data)
print("Mean using scipy.stats:", mean_value)

# Perform a one-sample t-test (testing if mean = 12)
t_stat, p_value = stats.ttest_1samp(data, 12)
print("t-statistic:", t_stat)
print("p-value:", p_value)


Mean using scipy.stats: 13.571428571428571
t-statistic: 2.0083160441856087
p-value: 0.09136743471209888


In [ ]:
from scipy import integrate
import math

# Define the function to integrate
def f(x):
    return x**2 + 3*x + 2

# Compute definite integral from x=0 to x=5
result, error = integrate.quad(f, 0, 5)
print("Definite Integral Result:", result)
print("Estimated Error:", error)


Definite Integral Result: 89.16666666666669
Estimated Error: 9.89948863624098e-13


In [ ]:
from scipy.optimize import minimize
def func(x):
    return x**2 + 4*x
    x0 = 0
result = minimize(func, x0)
print("Minimum Value:", result.fun)
print("At x =", result.x)


Minimum Value: -4.0
At x = [-2.00000001]
